### ISSUE TITLE
Resolve Iframe Issues on proposal.html and meetup.html

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.fund#4]
"Only one scrollbar per page" is what we're aiming for.

Currently these two pages have Google Forms embedded using an iframe. I added some javascript to make the form open to the full width, but apparently there are still two scrollbars.

**Comment by kauffj** [comment]
@NetOperatorWibby @jsigwart if you just set an inline style height on [this element](https://github.com/lbryio/lbry.fund/blob/master/proposal.html#L90) I think you're good to go.

Yes this an inelegant solution, doesn't work on mobile (since the form is a different height), and has to be adjusted whenever Julie changes the form, but it's simple :)

**Comment by kauffj** [comment]
i.e. `<div class="text-center embed-responsive embed-responsive-16by9" style="height: 2000px">`
